language: python
python:
  - 2.7
  - 3.4

env:
  - TOX_ENV=py27
  - TOX_ENV=py34

install:
  - pip install tox
  - pip install coveralls
  - pip install coverage

script:
  - tox -e $TOX_ENV

after_success:
  - coveralls
