language: python
python:
  - 2.7

env:
  - TOX_ENV=py33-1.6.X
  - TOX_ENV=py33-1.5.X
  - TOX_ENV=py27-1.6.X
  - TOX_ENV=py27-1.5.X

install:
  - pip install tox

script:
  - tox -e $TOX_ENV

after_success:
  - coveralls
